#!/bin/bash
# Builds Android client libraries to access the backend.

#python ~/Development/google_appengine/endpointscfg.py get_client_lib java --application ./app -bs default app.Post


python client_library/endpointscfg_wrapper.py \
	 get_client_lib \
	 java \
	--application ./app \
	--output ./client_library/android \
	-bs gradle \
	 modules.facebook.api.FacebookLogin \
	 modules.users.api.Users \
	 modules.sports.api.Sports \
	 modules.chat.api.Chat

echo "Extracting"

cd ./client_library/android

rm -rf sportmate
unzip sportmate-v1.0.zip

cd ./sportmate

echo "Running gradle"

gradle install
