#!/bin/bash
# Builds Android client libraries to access the backend.

#python ~/Development/google_appengine/endpointscfg.py get_client_lib java --application ./app -bs default app.Post


python client_library/make_client_core.py get_client_lib java \
	--application ./app \
	--output ./client_library \
	-bs gradle \
	 modules.facebook.api.FacebookLogin \
	 modules.users.api.Users \
	 modules.sports.api.Sports

echo "Extracting"

cd ./client_library

rm -rf sportmate
unzip sportmate-v1.0.zip

cd ./sportmate

echo "Running gradle"

gradle install
