#!/bin/bash
# Builds Android client libraries to access the backend.

#python ~/Development/google_appengine/endpointscfg.py get_client_lib java --application ./app -bs default app.Post


python client_library/make_client_core.py get_client_lib java \
	--application ./app \
	--output ./client_library \
	-bs gradle \
	app.User \
	app.Friend \
	app.Post \
	app.Notification \
	app.Emotion

echo "Extracting"

cd ./client_library

rm -rf loudnews
unzip loudnews-v1.0.zip

cd ./loudnews

echo "Running gradle"

gradle install
