/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-21 at 13:59:34 UTC 
 * Modify at your own risk.
 */

package com.appspot.sportmate_api.sportmate.model;

/**
 * Message containing a Facebook account with the corresponding Sportmate user.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the sportmate. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModulesFacebookMessagesFacebookAccountWithUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("access_token")
  private java.lang.String accessToken;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime expires;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("facebook_id") @com.google.api.client.json.JsonString
  private java.lang.Long facebookId;

  /**
   * Message containing the authenticated user.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ModulesUsersMessagesUserMe user;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccessToken() {
    return accessToken;
  }

  /**
   * @param accessToken accessToken or {@code null} for none
   */
  public ModulesFacebookMessagesFacebookAccountWithUser setAccessToken(java.lang.String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getExpires() {
    return expires;
  }

  /**
   * @param expires expires or {@code null} for none
   */
  public ModulesFacebookMessagesFacebookAccountWithUser setExpires(com.google.api.client.util.DateTime expires) {
    this.expires = expires;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFacebookId() {
    return facebookId;
  }

  /**
   * @param facebookId facebookId or {@code null} for none
   */
  public ModulesFacebookMessagesFacebookAccountWithUser setFacebookId(java.lang.Long facebookId) {
    this.facebookId = facebookId;
    return this;
  }

  /**
   * Message containing the authenticated user.
   * @return value or {@code null} for none
   */
  public ModulesUsersMessagesUserMe getUser() {
    return user;
  }

  /**
   * Message containing the authenticated user.
   * @param user user or {@code null} for none
   */
  public ModulesFacebookMessagesFacebookAccountWithUser setUser(ModulesUsersMessagesUserMe user) {
    this.user = user;
    return this;
  }

  @Override
  public ModulesFacebookMessagesFacebookAccountWithUser set(String fieldName, Object value) {
    return (ModulesFacebookMessagesFacebookAccountWithUser) super.set(fieldName, value);
  }

  @Override
  public ModulesFacebookMessagesFacebookAccountWithUser clone() {
    return (ModulesFacebookMessagesFacebookAccountWithUser) super.clone();
  }

}
