/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-21 at 13:59:34 UTC 
 * Modify at your own risk.
 */

package com.appspot.sportmate_api.sportmate.model;

/**
 * Message from an authenicated user responding to a friend request.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the sportmate. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UsersMessagesFriendRequestResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean accept;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String token;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long user;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAccept() {
    return accept;
  }

  /**
   * @param accept accept or {@code null} for none
   */
  public UsersMessagesFriendRequestResponse setAccept(java.lang.Boolean accept) {
    this.accept = accept;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToken() {
    return token;
  }

  /**
   * @param token token or {@code null} for none
   */
  public UsersMessagesFriendRequestResponse setToken(java.lang.String token) {
    this.token = token;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUser() {
    return user;
  }

  /**
   * @param user user or {@code null} for none
   */
  public UsersMessagesFriendRequestResponse setUser(java.lang.Long user) {
    this.user = user;
    return this;
  }

  @Override
  public UsersMessagesFriendRequestResponse set(String fieldName, Object value) {
    return (UsersMessagesFriendRequestResponse) super.set(fieldName, value);
  }

  @Override
  public UsersMessagesFriendRequestResponse clone() {
    return (UsersMessagesFriendRequestResponse) super.clone();
  }

}
